//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forma_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baqat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baqat()
        {
            this.Subscribes = new HashSet<Subscribe>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DaysPerMonth { get; set; }
        public Nullable<int> MaxDaysPerWeek { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribe> Subscribes { get; set; }
    }
}
